class State:
    BROWSE = "BROWSE"
    NEW_FILE = "NEW_FILE"
    NEW_FOLDER = "NEW_FOLDER"
    SEARCH_INPUT = "SEARCH_INPUT"
    SEARCH_RESULT = "SEARCH_RESULT"
    DELETE = "DELETE"

    COMMAND = "COMMAND"